version: '3.9'

services:
  client:
    container_name: cashforce_client
    build: ./client
    ports:
      - 5173:5173
    restart: always
    env_file:
      - ./client/.env
    depends_on:
      - server

  server:
    container_name: cashforce_api
    build: ./server
    ports:
      - 3001:3001
    restart: always
    env_file:
      - ./server/.env
    environment:
      - DB_HOST=db
    depends_on:
      db:
        condition: service_healthy

  db:
    image: mysql:8.0
    container_name: cashforce_db
    ports:
      - 3306:3306
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: 1234
    healthcheck:
      test: [ "CMD", "mysqladmin", "ping", "-h", "localhost" ]
      timeout: 10s
      retries: 5
